name: CI

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - run: npm install
    - run: tsc
    - run: npm start
    - run: curl "http://localhost:3000/users/test_user" -s -o /dev/null -w  "%{time_starttransfer}\n"
