name: CI

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - run: npm test
    - run: npm coverage
    - run: npm start
